name: Continuous Integration
on:
  push:
    branches:
      - '*'

jobs:

  lint:
    name: lint
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: ci
    steps:
    - name: Check out the code
      uses: actions/checkout@v2
    - name: Run lint
      run: make go-lint

  test:
    name: test
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: ci
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
      - name: Run test
        run: make go-test

  build:
    name: build
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: ci
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
      - name: Run build
        run: make go-build
